/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objetos.*;
import Componentes.*;
import java.awt.Color;
import java.awt.Graphics;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author onascimento
 */
public class Principal extends javax.swing.JFrame {

    Display dsp;
    Poligono axisX, axisY;
    Poligono polAux;
    Ponto pAux;
    Janela viewPort;
    Janela world;
    Janela clip;
    DefaultListModel listaPoligono;
    DefaultListModel listaPontos;

    int AddPoligono;

    /**
     * Creates new form Principal
     */
    public Principal() {
        pAux = new Ponto();
        polAux = new Poligono();
        dsp = new Display();

        listaPoligono = new DefaultListModel();
        listaPontos = new DefaultListModel();

        viewPort = new Janela(0, 0, 500, 500);
        world = new Janela(-250, -250, 250, 250);
        clip = new Janela(-100, -100, 100, 100);
        AddPoligono = 0;
        initComponents();

        axisY = new Poligono();
        axisY.pontos.add(new Ponto(0, -250));
        axisY.pontos.add(new Ponto(0, 250));

        axisX = new Poligono();
        axisX.pontos.add(new Ponto(-250, 0));
        axisX.pontos.add(new Ponto(250, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnNovoPoligono = new javax.swing.JButton();
        canvas = new java.awt.Canvas();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlsPoligonos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlsPontos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlbMundo = new javax.swing.JLabel();
        jlbView = new javax.swing.JLabel();
        jcbModDesenho = new javax.swing.JComboBox<>();
        jbtnDesenha = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtnParaCima = new javax.swing.JButton();
        jbtnParaDireita = new javax.swing.JButton();
        jbtnParaEsquerda = new javax.swing.JButton();
        jbtnParaBaixo = new javax.swing.JButton();
        jbtnParaOrigem = new javax.swing.JButton();
        jtxtxMin = new javax.swing.JTextField();
        jtxtxMax = new javax.swing.JTextField();
        jtxtyMin = new javax.swing.JTextField();
        jtxtyMax = new javax.swing.JTextField();
        jbtnAtualizaMundo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jchbX = new javax.swing.JCheckBox();
        jchbY = new javax.swing.JCheckBox();
        jbtnRefletir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jtxtYd1 = new javax.swing.JTextField();
        jtxtXd1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtnTransladar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jtxtGraus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbtnRotaciona = new javax.swing.JButton();
        jrbHomogenia = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jtxtXd = new javax.swing.JTextField();
        jtxtYd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnEscalonar = new javax.swing.JButton();
        jrbLinhas = new javax.swing.JRadioButton();
        jrbCircunferencia = new javax.swing.JRadioButton();
        jrbCurvas = new javax.swing.JRadioButton();
        jcbCurvas = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jbtnClipping = new javax.swing.JButton();
        jtxtyMin1 = new javax.swing.JTextField();
        jtxtyMax1 = new javax.swing.JTextField();
        jtxtxMax1 = new javax.swing.JTextField();
        jtxtxMin1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jbtnReadFile = new javax.swing.JButton();
        jtxtCaminho = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtxtGraus1 = new javax.swing.JTextField();
        jbtnRotaciona1 = new javax.swing.JButton();
        jchbY1 = new javax.swing.JCheckBox();
        jchbX1 = new javax.swing.JCheckBox();
        jchbZ = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtxtYd2 = new javax.swing.JTextField();
        jtxtXd2 = new javax.swing.JTextField();
        jbtnEscalonar1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jtxtXd3 = new javax.swing.JTextField();
        jtxtYd3 = new javax.swing.JTextField();
        jbtnTransladar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtnDesenhaCanvas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbtnNovoPoligono.setText("Novo Poligono");
        jbtnNovoPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoPoligonoActionPerformed(evt);
            }
        });

        canvas.setBackground(new java.awt.Color(102, 102, 102));
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
        });
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvasMouseMoved(evt);
            }
        });

        jlsPoligonos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jlsPoligonosComponentAdded(evt);
            }
        });
        jlsPoligonos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlsPoligonosKeyPressed(evt);
            }
        });
        jlsPoligonos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlsPoligonosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlsPoligonos);

        jLabel1.setText("Poligonos: ");

        jScrollPane2.setViewportView(jlsPontos);

        jLabel2.setText("Pontos: ");

        jLabel3.setText("Coord. Mundo: ");

        jLabel4.setText("Coord. ViewPort: ");

        jlbMundo.setText("jLabel5");

        jlbView.setText("jLabel5");

        jcbModDesenho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metodo de Desenho", "Default", "DDA", "Bresenham" }));
        jcbModDesenho.setSelectedIndex(1);

        jbtnDesenha.setText("Limpar Canvas");
        jbtnDesenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDesenhaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle de View"));

        jbtnParaCima.setText("^");
        jbtnParaCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParaCimaActionPerformed(evt);
            }
        });

        jbtnParaDireita.setText(">");
        jbtnParaDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParaDireitaActionPerformed(evt);
            }
        });

        jbtnParaEsquerda.setText("<");
        jbtnParaEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParaEsquerdaActionPerformed(evt);
            }
        });

        jbtnParaBaixo.setText("v");
        jbtnParaBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParaBaixoActionPerformed(evt);
            }
        });

        jbtnParaOrigem.setText("Reset");
        jbtnParaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParaOrigemActionPerformed(evt);
            }
        });

        jtxtxMin.setText("xMin");

        jtxtxMax.setText("xMax");
        jtxtxMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtxMaxActionPerformed(evt);
            }
        });

        jtxtyMin.setText("yMin");

        jtxtyMax.setText("yMax");

        jbtnAtualizaMundo.setText("Atualiza Mundo");
        jbtnAtualizaMundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtualizaMundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnParaEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnParaBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnParaCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnParaOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnParaDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbtnAtualizaMundo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtyMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtyMax))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtxMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtxMax)))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnParaCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnParaBaixo)
                            .addComponent(jbtnParaDireita)
                            .addComponent(jbtnParaEsquerda)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtxMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtyMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtyMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnParaOrigem)
                    .addComponent(jbtnAtualizaMundo))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jchbX.setText("X");

        jchbY.setText("Y");

        jbtnRefletir.setText("Refletir");
        jbtnRefletir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRefletirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnRefletir)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jchbX)
                        .addGap(18, 18, 18)
                        .addComponent(jchbY)))
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchbX)
                    .addComponent(jchbY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRefletir)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reflexao", jPanel3);

        jtxtYd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtYd1ActionPerformed(evt);
            }
        });

        jLabel8.setText("X: ");

        jbtnTransladar.setText("Transladar");
        jbtnTransladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTransladarActionPerformed(evt);
            }
        });

        jLabel9.setText("Y: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTransladar)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtXd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtYd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtXd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtYd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTransladar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transladar", jPanel4);

        jLabel10.setText("Graus: ");

        jbtnRotaciona.setText("Rotaciona");
        jbtnRotaciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRotacionaActionPerformed(evt);
            }
        });

        jrbHomogenia.setText("Homogenia");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jbtnRotaciona))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(jtxtGraus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbHomogenia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtGraus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jrbHomogenia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRotaciona)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rotacionar", jPanel5);

        jtxtYd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtYdActionPerformed(evt);
            }
        });

        jLabel6.setText("X: ");

        jLabel7.setText("Y: ");

        jbtnEscalonar.setText("Escalonar");
        jbtnEscalonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEscalonarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnEscalonar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxtXd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtYd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtXd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtYd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnEscalonar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Escalonar", jPanel2);

        jrbLinhas.setSelected(true);
        jrbLinhas.setText("Linhas");
        jrbLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLinhasActionPerformed(evt);
            }
        });

        jrbCircunferencia.setText("Circunferencia");
        jrbCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCircunferenciaActionPerformed(evt);
            }
        });

        jrbCurvas.setText("Curvas");
        jrbCurvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCurvasActionPerformed(evt);
            }
        });

        jcbCurvas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casteuljau", "Hermite", "Bezier", "B-Spline" }));
        jcbCurvas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCurvasItemStateChanged(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Clipping"));

        jbtnClipping.setText("Clip Poligonos");
        jbtnClipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClippingActionPerformed(evt);
            }
        });

        jtxtyMin1.setText("yMin");

        jtxtyMax1.setText("yMax");

        jtxtxMax1.setText("xMax");
        jtxtxMax1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtxMax1ActionPerformed(evt);
            }
        });

        jtxtxMin1.setText("xMin");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtyMin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtyMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtxMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtxMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jbtnClipping)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtxMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtxMax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtyMax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtyMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnClipping)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("3D"));

        jbtnReadFile.setText("...");
        jbtnReadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReadFileActionPerformed(evt);
            }
        });

        jtxtCaminho.setText("Caminho | *.txt");

        jLabel15.setText("Graus: ");

        jbtnRotaciona1.setText("Rotaciona");
        jbtnRotaciona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRotaciona1ActionPerformed(evt);
            }
        });

        jchbY1.setText("Y");

        jchbX1.setText("X");

        jchbZ.setText("Z");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(12, 12, 12)
                        .addComponent(jtxtGraus1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jchbX1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchbY1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchbZ)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnRotaciona1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbX1)
                            .addComponent(jchbY1)
                            .addComponent(jchbZ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jtxtGraus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbtnRotaciona1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Rotacionar", jPanel10);

        jLabel11.setText("X: ");

        jtxtYd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtYd2ActionPerformed(evt);
            }
        });

        jbtnEscalonar1.setText("Escalonar");
        jbtnEscalonar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEscalonar1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Y: ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnEscalonar1)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jtxtXd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtYd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtXd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtYd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnEscalonar1)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Escalonar", jPanel9);

        jtxtYd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtYd3ActionPerformed(evt);
            }
        });

        jbtnTransladar1.setText("Transladar");
        jbtnTransladar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTransladar1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Y: ");

        jLabel13.setText("X: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTransladar1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jtxtXd3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtYd3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtXd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtYd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTransladar1)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Transladar", jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jtxtCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnReadFile)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReadFile)
                    .addComponent(jtxtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnDesenhaCanvas.setText("Desenha Todos Poligonos");
        jbtnDesenhaCanvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDesenhaCanvasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbMundo)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnNovoPoligono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jrbLinhas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jrbCircunferencia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrbCurvas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbCurvas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jcbModDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnDesenhaCanvas)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnDesenha)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnNovoPoligono)
                            .addComponent(jrbLinhas)
                            .addComponent(jrbCircunferencia)
                            .addComponent(jrbCurvas)
                            .addComponent(jcbCurvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbModDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnDesenhaCanvas)
                            .addComponent(jbtnDesenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbMundo)
                            .addComponent(jLabel4)
                            .addComponent(jlbView))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseMoved
        // TODO add your handling code here:
        pAux.setX(evt.getX());
        pAux.setY(evt.getY());
        jlbMundo.setText("(" + (int) pAux.getX() + "," + (int) pAux.getY() + ")");
        jlbView.setText("(" + pAux.XwvP((int) pAux.getX(), viewPort, world) + "," + pAux.YwvP((int) pAux.getY(), viewPort, world) + ")");
    }//GEN-LAST:event_canvasMouseMoved

    public void desenhaEixosFixo() {
        Graphics g = canvas.getGraphics();
        g.setColor(Color.red);

        AtualizaMundo(world);

        g.drawLine(pAux.XwvP((int) axisX.pontos.get(0).getX(), world, viewPort), pAux.YwvP((int) axisX.pontos.get(0).getY(), world, viewPort), pAux.XwvP((int) axisX.pontos.get(1).getX(), world, viewPort), pAux.YwvP((int) axisX.pontos.get(1).getY(), world, viewPort));
        g.drawLine(pAux.XwvP((int) axisY.pontos.get(0).getX(), world, viewPort), pAux.YwvP((int) axisY.pontos.get(0).getY(), world, viewPort), pAux.XwvP((int) axisY.pontos.get(1).getX(), world, viewPort), pAux.YwvP((int) axisY.pontos.get(1).getY(), world, viewPort));

        g.drawLine(pAux.XwvP((int) clip.getMinX(), world, viewPort), pAux.YwvP((int) clip.getMinY(), world, viewPort), pAux.XwvP((int) clip.getMinX(), world, viewPort), pAux.YwvP((int) clip.getMaxY(), world, viewPort));
        g.drawLine(pAux.XwvP((int) clip.getMinX(), world, viewPort), pAux.YwvP((int) clip.getMaxY(), world, viewPort), pAux.XwvP((int) clip.getMaxX(), world, viewPort), pAux.YwvP((int) clip.getMaxY(), world, viewPort));
        g.drawLine(pAux.XwvP((int) clip.getMaxX(), world, viewPort), pAux.YwvP((int) clip.getMaxY(), world, viewPort), pAux.XwvP((int) clip.getMaxX(), world, viewPort), pAux.YwvP((int) clip.getMinY(), world, viewPort));
        g.drawLine(pAux.XwvP((int) clip.getMaxX(), world, viewPort), pAux.YwvP((int) clip.getMinY(), world, viewPort), pAux.XwvP((int) clip.getMinX(), world, viewPort), pAux.YwvP((int) clip.getMinY(), world, viewPort));
    }

    public void reDesenha() {
        canvas.getGraphics().clearRect(0, 0, 500, 500);
        desenhaEixosFixo();
    }

    public void AtualizaMundo(Janela mundo) {
        axisY.pontos.get(0).setY(mundo.getMaxY());
        axisY.pontos.get(1).setY(mundo.getMinY());
        
        axisX.pontos.get(0).setX(mundo.getMaxX());
        axisX.pontos.get(1).setX(mundo.getMinX());
    }

    public void desenhaCanvas() {
        if (jcbModDesenho.getSelectedIndex() == 1) {
            for (int i = 0; i < dsp.getPoligonos().size(); i++) {
                dsp.getPoligonos().get(i).draw(canvas, viewPort, world);
            }
        } else {
            if (jcbModDesenho.getSelectedIndex() == 2) {
                for (int i = 0; i < dsp.getPoligonos().size(); i++) {
                    dsp.getPoligonos().get(i).drawDda(canvas, viewPort, world);
                }
            } else {
                if (jcbModDesenho.getSelectedIndex() == 3) {
                    for (int i = 0; i < dsp.getPoligonos().size(); i++) {
                        dsp.getPoligonos().get(i).drawBresenham(canvas, viewPort, world);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Escolha o Metodo de Desenho");
                }
            }
        }
    }

    public void desenhaPoligono() {
        int i = jlsPoligonos.getSelectedIndex();
        Poligono p = dsp.getPoligonos().get(i);

        if (jcbModDesenho.getSelectedIndex() == 1) {
            p.draw(canvas, viewPort, world);
        } else {
            if (jcbModDesenho.getSelectedIndex() == 2) {
                p.drawDda(canvas, viewPort, world);
            } else {
                if (jcbModDesenho.getSelectedIndex() == 3) {
                    p.drawBresenham(canvas, viewPort, world);
                } else {
                    JOptionPane.showMessageDialog(null, "Escolha o Metodo de Desenho");
                }
            }
        }
    }

    private void jbtnNovoPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoPoligonoActionPerformed
        // TODO add your handling code here:     
        if (AddPoligono == 0) {
            jbtnNovoPoligono.setText("Termina Poligono");
            AddPoligono = 1;

            desenhaEixosFixo();//POG

        } else {
            //Adiciona ao DisplayFile e Depois desenha colocando o AdcionaPol = 0;
            if (0 == polAux.getPontos().size()) {
                JOptionPane.showMessageDialog(null, "Clique no Painel para adicionar os pontos ao poligono");
            } else {
                if (polAux.tipo == 2) {
                    polAux = polAux.drawCirculo(polAux.getPontos().get(0), polAux.getPontos().get(1));
                    dsp.poligonos.add(polAux);
                    polAux = new Poligono(2);
                } else {
                    if (polAux.tipo == 3) {
                        polAux.draw(canvas, viewPort, world);
                        if (jcbCurvas.getSelectedIndex() == 0) {
                            polAux.CalculaCurvaCasteljau();
                        }
                        if (jcbCurvas.getSelectedIndex() == 1) {
                            polAux = polAux.curvaHermite();
                        }
                        if (jcbCurvas.getSelectedIndex() == 2) {
                            polAux = polAux.curvaBezier();
                        }
                        if (jcbCurvas.getSelectedIndex() == 3) {
                            polAux = polAux.bSpline();
                        }
                        dsp.poligonos.add(polAux);
                        polAux = new Poligono(3);
                    } else {
                        dsp.poligonos.add(polAux);
                        polAux = new Poligono();
                    }
                }

                jbtnNovoPoligono.setText("Novo Poligono");
                AddPoligono = 0;

                listaPoligono.addElement(dsp.poligonos.size());
                try {
                    jlsPoligonos.setModel(listaPoligono);
                } catch (Exception e) {
                }
                desenhaCanvas();

            }
        }
    }//GEN-LAST:event_jbtnNovoPoligonoActionPerformed

    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
        // TODO add your handling code here:
        Ponto pAux2 = new Ponto();

        if (AddPoligono == 0) {
            JOptionPane.showMessageDialog(null, "Clique em Novo poligono primeiro");
        } else {
            pAux2.setX(pAux.XwvP(evt.getX(), viewPort, world));
            pAux2.setY(pAux.YwvP(evt.getY(), viewPort, world));
            polAux.pontos.add(pAux2);
        }
    }//GEN-LAST:event_canvasMouseClicked

    private void jlsPoligonosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlsPoligonosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlsPoligonosKeyPressed

    private void jlsPoligonosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlsPoligonosValueChanged
        // TODO add your handling code here:
        listaPontos.clear();

        dsp.poligonos.get(jlsPoligonos.getSelectedIndex()).pontos.forEach((p) -> {
            listaPontos.addElement(p);
        });

        jlsPontos.setModel(listaPontos);
        reDesenha();
        desenhaPoligono();
    }//GEN-LAST:event_jlsPoligonosValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jcbCurvas.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jbtnDesenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDesenhaActionPerformed
        // TODO add your handling code here:
        reDesenha();
    }//GEN-LAST:event_jbtnDesenhaActionPerformed

    private void jbtnParaCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParaCimaActionPerformed
        // TODO add your handling code here:

        world.setMaxY(world.getMaxY() + 5);
        world.setMinY(world.getMinY() + 5);

        reDesenha();
        canvas.update(this.getGraphics());
        desenhaCanvas();
    }//GEN-LAST:event_jbtnParaCimaActionPerformed

    private void jbtnParaDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParaDireitaActionPerformed
        // TODO add your handling code here:

        world.setMaxX(world.getMaxX() + 5);
        world.setMinX(world.getMinX() + 5);

        reDesenha();
        canvas.update(this.getGraphics());
        desenhaCanvas();
    }//GEN-LAST:event_jbtnParaDireitaActionPerformed

    private void jbtnParaEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParaEsquerdaActionPerformed
        // TODO add your handling code here:

        world.setMaxX(world.getMaxX() - 5);
        world.setMinX(world.getMinX() - 5);

        reDesenha();
        canvas.update(this.getGraphics());
        desenhaCanvas();
    }//GEN-LAST:event_jbtnParaEsquerdaActionPerformed

    private void jbtnParaBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParaBaixoActionPerformed
        // TODO add your handling code here:
        world.setMaxY(world.getMaxY() - 5);
        world.setMinY(world.getMinY() - 5);

        reDesenha();
        canvas.update(this.getGraphics());
        desenhaCanvas();

    }//GEN-LAST:event_jbtnParaBaixoActionPerformed

    private void jbtnParaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParaOrigemActionPerformed
        // TODO add your handling code here:

        world.setMaxY(250);
        world.setMinY(-250);
        world.setMaxX(250);
        world.setMinX(-250);
        reDesenha();
        canvas.update(this.getGraphics());
        desenhaCanvas();

    }//GEN-LAST:event_jbtnParaOrigemActionPerformed

    private void jbtnEscalonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEscalonarActionPerformed
        // TODO add your handling code here:
        Float xD = Float.parseFloat(jtxtXd.getText());
        Float yD = Float.parseFloat(jtxtYd.getText());

        dsp.getPoligonos().get(jlsPoligonos.getSelectedIndex()).escalonar(xD, yD);
        reDesenha();
        desenhaPoligono();
    }//GEN-LAST:event_jbtnEscalonarActionPerformed

    private void jtxtYdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtYdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtYdActionPerformed

    private void jbtnRefletirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRefletirActionPerformed
        // TODO add your handling code here:
        if (jchbX.isSelected() && jchbY.isSelected()) {
            dsp.getPoligonos().get(jlsPoligonos.getSelectedIndex()).reflexao(2);
        } else {
            if (jchbX.isSelected()) {
                dsp.getPoligonos().get(jlsPoligonos.getSelectedIndex()).reflexao(1);
            } else {
                dsp.getPoligonos().get(jlsPoligonos.getSelectedIndex()).reflexao(0);
            }
        }
        reDesenha();
        desenhaPoligono();
    }//GEN-LAST:event_jbtnRefletirActionPerformed

    private void jbtnTransladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTransladarActionPerformed
        // TODO add your handling code here:
        int xD = Integer.parseInt(jtxtXd1.getText());
        int yD = Integer.parseInt(jtxtYd1.getText());

        dsp.getPoligonos().get(jlsPoligonos.getSelectedIndex()).transladar(xD, yD);
        reDesenha();
        desenhaPoligono();
    }//GEN-LAST:event_jbtnTransladarActionPerformed

    private void jtxtYd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtYd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtYd1ActionPerformed

    private void jbtnRotacionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRotacionaActionPerformed
        // TODO add your handling code here:
        int graus = Integer.parseInt(jtxtGraus.getText());
        Poligono p = dsp.getPoligonos().get(jlsPoligonos.getSelectedIndex());
        if(jrbHomogenia.isSelected()){
            p.rotacionar(graus);
        }else{
            p.rotacionar(p, graus);
        }
        reDesenha();
        desenhaPoligono();

    }//GEN-LAST:event_jbtnRotacionaActionPerformed

    private void jtxtxMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtxMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtxMaxActionPerformed

    private void jbtnAtualizaMundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtualizaMundoActionPerformed
        // TODO add your handling code here:
        world.setMaxY(Integer.parseInt(jtxtyMax.getText()));
        world.setMinY(Integer.parseInt(jtxtyMin.getText()));
        world.setMaxX(Integer.parseInt(jtxtxMax.getText()));
        world.setMinX(Integer.parseInt(jtxtxMin.getText()));
        reDesenha();
        canvas.update(this.getGraphics());
        desenhaCanvas();
        
    }//GEN-LAST:event_jbtnAtualizaMundoActionPerformed

    private void jrbLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLinhasActionPerformed
        // TODO add your handling code here:
        jrbCircunferencia.setSelected(false);
        jrbCurvas.setSelected(false);
        polAux = new Poligono();
        jcbCurvas.setVisible(false);
    }//GEN-LAST:event_jrbLinhasActionPerformed

    private void jrbCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCircunferenciaActionPerformed
        // TODO add your handling code here:
        jrbLinhas.setSelected(false);
        jrbCurvas.setSelected(false);
        polAux = new Poligono(2);
        jcbCurvas.setVisible(false);
        JOptionPane.showMessageDialog(null, "Selecione dois pontos");
    }//GEN-LAST:event_jrbCircunferenciaActionPerformed

    private void jbtnClippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClippingActionPerformed
        // TODO add your handling code here:
        int i, j=0;
        try{
            int xMax,xMin,yMax,yMin;
            xMax = Integer.parseInt(jtxtxMax1.getText());
            xMin = Integer.parseInt(jtxtxMin1.getText());
            yMax = Integer.parseInt(jtxtyMax1.getText());
            yMin = Integer.parseInt(jtxtyMin1.getText());
            
            clip = new Janela(xMin,yMin,xMax,yMax);
        }catch(Exception e){}
        
        for (i = 0; i < dsp.getPoligonos().size(); i++) {
            if (dsp.getPoligonos().get(i).tipo == 4) {
                j++;
            }
        }

        j *= 2;
        i = dsp.getPoligonos().size();

        for (; j < i; j++) {
            Poligono aux = new Poligono();
            aux.pontos = dsp.getPoligonos().get(j).pontos;
            aux.clip(clip.getMinX(), clip.getMinY(), clip.getMaxX(), clip.getMaxY());
            if(!aux.pontos.isEmpty()){
                dsp.poligonos.add(aux);
                listaPoligono.addElement(dsp.getPoligonos().size() + "(CLIP)");
            }
        }
        reDesenha();
        desenhaCanvas();
    }//GEN-LAST:event_jbtnClippingActionPerformed

    private void jlsPoligonosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jlsPoligonosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jlsPoligonosComponentAdded

    private void jrbCurvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCurvasActionPerformed
        // TODO add your handling code here:
        jrbCircunferencia.setSelected(false);
        jrbLinhas.setSelected(false);
        polAux = new Poligono(3);
        jcbCurvas.setVisible(true);
    }//GEN-LAST:event_jrbCurvasActionPerformed

    private void jcbCurvasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCurvasItemStateChanged
        // TODO add your handling code here:
        polAux = new Poligono(3);
    }//GEN-LAST:event_jcbCurvasItemStateChanged

    private void jtxtxMax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtxMax1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtxMax1ActionPerformed

    private void jtxtYd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtYd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtYd2ActionPerformed

    private void jbtnEscalonar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEscalonar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEscalonar1ActionPerformed

    private void jtxtYd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtYd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtYd3ActionPerformed

    private void jbtnTransladar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTransladar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTransladar1ActionPerformed

    private void jbtnRotaciona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRotaciona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRotaciona1ActionPerformed

    private void jbtnReadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReadFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        Scanner sc;
        File f;
        int x,y,z;
        String aux;
        
        chooser.showOpenDialog(Principal.this);
        f = chooser.getSelectedFile();

        jtxtCaminho.setText(f.getPath());
        FileReader arq;
        try {
            arq = new FileReader(f.getPath());
            BufferedReader lerArq = new BufferedReader(arq);

            String linha = lerArq.readLine();
            Poligono pol3D = new Poligono(new Ponto(),0);
            
            while (linha != null) {
                sc = new Scanner(linha);
                int i=0;
                int valoresXYZ[] = null;
                while(sc.hasNext()){
                    aux = sc.next();
                    if(tryConversion(aux)){
                        valoresXYZ[i] = Integer.parseInt(aux);
                    }
                    i++;
                }
                
                x = valoresXYZ[0];
                y = valoresXYZ[1];
                z = valoresXYZ[2];
                
                Ponto p = new Ponto(x,y);
                pol3D.getPontos3D().add(i, new Ponto3D(p,z));
                linha = lerArq.readLine();
            }
            
            for(Ponto3D p: pol3D.getPontos3D()){
                System.out.println(p.z);
            }
            
        } catch (Exception e) {
            System.out.println("DEU RUIM");
        }
    }//GEN-LAST:event_jbtnReadFileActionPerformed
    
    public boolean tryConversion(String st) {
        try {
            Integer.parseInt(st);
            return true;
        } catch (NumberFormatException nb) {
            return false;
        }
    }
    
    private void jbtnDesenhaCanvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDesenhaCanvasActionPerformed
        // TODO add your handling code here:
        reDesenha();
        desenhaCanvas();
    }//GEN-LAST:event_jbtnDesenhaCanvasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbtnAtualizaMundo;
    private javax.swing.JButton jbtnClipping;
    private javax.swing.JButton jbtnDesenha;
    private javax.swing.JButton jbtnDesenhaCanvas;
    private javax.swing.JButton jbtnEscalonar;
    private javax.swing.JButton jbtnEscalonar1;
    private javax.swing.JButton jbtnNovoPoligono;
    private javax.swing.JButton jbtnParaBaixo;
    private javax.swing.JButton jbtnParaCima;
    private javax.swing.JButton jbtnParaDireita;
    private javax.swing.JButton jbtnParaEsquerda;
    private javax.swing.JButton jbtnParaOrigem;
    private javax.swing.JButton jbtnReadFile;
    private javax.swing.JButton jbtnRefletir;
    private javax.swing.JButton jbtnRotaciona;
    private javax.swing.JButton jbtnRotaciona1;
    private javax.swing.JButton jbtnTransladar;
    private javax.swing.JButton jbtnTransladar1;
    private javax.swing.JComboBox<String> jcbCurvas;
    private javax.swing.JComboBox<String> jcbModDesenho;
    private javax.swing.JCheckBox jchbX;
    private javax.swing.JCheckBox jchbX1;
    private javax.swing.JCheckBox jchbY;
    private javax.swing.JCheckBox jchbY1;
    private javax.swing.JCheckBox jchbZ;
    private javax.swing.JLabel jlbMundo;
    private javax.swing.JLabel jlbView;
    private javax.swing.JList<String> jlsPoligonos;
    private javax.swing.JList<String> jlsPontos;
    private javax.swing.JRadioButton jrbCircunferencia;
    private javax.swing.JRadioButton jrbCurvas;
    private javax.swing.JRadioButton jrbHomogenia;
    private javax.swing.JRadioButton jrbLinhas;
    private javax.swing.JTextField jtxtCaminho;
    private javax.swing.JTextField jtxtGraus;
    private javax.swing.JTextField jtxtGraus1;
    private javax.swing.JTextField jtxtXd;
    private javax.swing.JTextField jtxtXd1;
    private javax.swing.JTextField jtxtXd2;
    private javax.swing.JTextField jtxtXd3;
    private javax.swing.JTextField jtxtYd;
    private javax.swing.JTextField jtxtYd1;
    private javax.swing.JTextField jtxtYd2;
    private javax.swing.JTextField jtxtYd3;
    private javax.swing.JTextField jtxtxMax;
    private javax.swing.JTextField jtxtxMax1;
    private javax.swing.JTextField jtxtxMin;
    private javax.swing.JTextField jtxtxMin1;
    private javax.swing.JTextField jtxtyMax;
    private javax.swing.JTextField jtxtyMax1;
    private javax.swing.JTextField jtxtyMin;
    private javax.swing.JTextField jtxtyMin1;
    // End of variables declaration//GEN-END:variables
}
